# VoidCurrency
# Developed by Mantice

debug-mode: true

storage:
  # SQLite or MySQL
  # Requires server restart to change storage settings!
  type: SQLite
  mysql:
    host: 0.0.0.0
    port: 3306
    database: voidcurrency
    username: username
    password: password
    pool: 10

modules:
  # Enable/disable certain aspects of the plugin!
  # Requires restart!
  balance: true
  pay: true